// tuf-search: #passSubmissionInitialForm #passSubmission
export const PASS_SUBMISSION_INITIAL_FORM = {
  levelId: '',
  videoLink: '',
  playerId: '',
  leaderboardName: '',
  speed: '',
  keyCount: '',
  feelingRating: '',
  expectedRating: '',
  ePerfect: '',
  perfectMinus: '',
  perfect: '',
  perfectPlus: '',
  lPerfect: '',
  tooEarly: '',
  early: '',
  late: '',
  isNoHold: false,
  isAdofaiV2: false,
  adofaiVersion: 3,
  isXPerfectMode: false,
  passMetaFlags: 0,
};
